### ISSUE TITLE
Automatic code checking

### ISSUE THREAD

**Issue by heinermann** [Quinny/uWindsor-POTW-Leaderboard#6]
Automated compilation and verification of problem of the week (just like an online judge).

Complexity verification is up in the air.

**Comment by Quinny** [comment]
There are a couple issues regarding this.  One thing is that I would like to keep it so that you can use any language you want, and it would be hard to keep up with that automatically.  Also there would have to be a system that reads the code and make sure no mallicous calls were being made (mallocing a ton of memory and then just leaving it, etc.) Also as you mentenioned complexity and memory requirements (although that could be enforced with time limits)

**Comment by heinermann** [comment]
This is what virtual machines are for. You would spawn a VM for each submission. If the VM doesn't respond after x minutes you terminate it and report a TLE.

**Comment by Quinny** [comment]
Yeah that could work, I would have to see about doing that on my host.  I couldn't get django deployed on the uwindsor server because it doesn't have the right modules installed

**Comment by heinermann** [comment]
http://www.quora.com/How-can-I-build-a-small-level-online-judge-like-the-one-used-by-SPOJ-UVa-HackerRank

https://github.com/darbula/django-onlinejudge

**Comment by heinermann** [comment]
https://github.com/darbula/django-onlinejudge

**Comment by Quinny** [comment]
I think for now this will have to be put in the background.  The problems aren't really suited well for automatic judging and it seems like too much work to be worth it at this point.
